name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta cada dÃ­a a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: andreaonweb
          outputs: dist/github-contribution-grid-snake.svg
- name: Push generated snake
  uses: crazy-max/ghaction-github-pages@v4
  with:
    target_branch: output
    build_dir: dist
    commit_message: "ğŸ update snake animation"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
